### ISSUE TITLE
Missing package dependency "past"

### ISSUE THREAD

**Issue by ufo** [erocarrera/pefile#101]
Hi,
since yesterday I'm getting this exception:
  File "/tmp/easy_install-pqXztQ/pefile-2016.3.4/pefile.py", line 26, in <module>
ImportError: No module named past.builtins
Looking into the source resp. the package setup I'm wondering how it might work for anybody at all?
Shouldn't the package setup also list "past" inside of "install_requires"?
Regards

**Comment by ufo** [comment]
Sry.. wrong assumption.

**Comment by techtonik** [comment]
[past.builtins](http://python-future.org/reference.html#module-past.builtins) is actually in `requirements.txt`
