### ISSUE TITLE
Wrong information displayed in Exported symbols

### ISSUE THREAD

**Issue by kdeltared** [erocarrera/pefile#103]
The Exported symbols section is displaying wrong information. The ordinal numbers and RVAs do not match with the analysis made by pestudio and IDA pro. For testing, I used kernle32.dll (sha2: e270d5032d2c8d9b226d69103e0fd94f023c82f04c1fc5e8bbd803b40611ea07).

This happens under Ubuntu with pefile version 2016.3.28, but the windows pefile version 1.2.10.post114 works fine.

Using python 2.7

**Comment by erocarrera** [comment]
From what I see both IDA and pefile show the same information. pefile does not add the ImageBase to the relative address of the export. The ordinal and name agree with IDA's reported values. And if you account for the ImageBase, the addresses match too.
I'll close the issue, if you can point me to specific values that disagree please feel free to reopen.
