### ISSUE TITLE
Error for value returned from get_overlay_data_start_offset()

### ISSUE THREAD

**Issue by cbmeyer** [erocarrera/pefile#104]
The current implementation of get_overlay_data_start_offset() includes the VirtualAddress and Size of the IMAGE_DIRECTORY_ENTRY structures, but that leads to an incorrect offset for the overlay of the file.  Here are two examples where the offset is calculated incorrectly:

https://www.virustotal.com/en/file/3096e39df63c0be68746ea3bbe528c067b6eb45e2d61cc167712c3b1e0966be3/analysis/, the overlay offset listed by VT corresponds to the IMAGE_DIRECTORY_ENTRY_SECURITY structure, which makes sense for certificate information, as digital signatures must be overlays.  However, the pefile module reports no overlay for this file, as the IMAGE_DIRECTORY_ENTRY_SECURITY VirtualAddress is equal to the largest section.PointerToRawData + section.SizeOfRawData, and the Size is the number of bytes from this VirtualAddress to the end of the file.

https://www.virustotal.com/en/file/307a69414b203f1116db677b8bc07130ae2b72cf33cf2ae5a39bf1bd484b587c/analysis/, the overlay offset listed by VT is the offset produced by the largest section.PointerToRawData + section.SizeOfRawData in the file, 14848, but the pefile module reports it as a larger value of 26176, as all of the IMAGE_DIRECTORY_ENTRY structures have virtual addresses larger than the largest section.PointerToRawData + section.SizeOfRawData.

**Comment by mtivadar** [comment]
this is indeed true, overlay is not correctly calculated.

**Comment by erocarrera** [comment]
These should have been fixed in #188

**Comment by recvfrom** [comment]
@erocarrera @cbmeyer @mtivadar Can we revisit this decision to treat the [Attribute Certificate Table](https://docs.microsoft.com/en-us/windows/desktop/debug/pe-format#the-attribute-certificate-table-image-only) data as overlay data?  Although it's true that this data gets added to the end of a PE file after compilation, this data isn't just a blob that gets appended - the size and RVA/offset of this data are explicitly recorded within the PE header.  If you were to remove the data, the PE would become invalid (which is not the case for real overlay data).

One side effect of this change is that it breaks scripts like this that attempt to compute the size of an exe based on the information in the PE header:
https://researchcenter.paloaltonetworks.com/2016/01/using-idapython-to-make-your-life-easier-part-5/
