### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 208687: ordinal not in range(128)

### ISSUE THREAD

**Issue by ibrahimkaraguzel** [erocarrera/pefile#105]
Hello;
I am ok with, while building and installing pefile via Python2.7. I got No errors.

Problem starts while building Python3.4:
`Building source...
Sandbox enabled build...
running build
running build_py
creating build
creating build/lib
copying pefile.py -> build/lib
copying peutils.py -> build/lib
creating build/lib/ordlookup
copying ordlookup/__init__.py -> build/lib/ordlookup
copying ordlookup/oleaut32.py -> build/lib/ordlookup
copying ordlookup/ws2_32.py -> build/lib/ordlookup
warning: build_py: byte-compiling is disabled, skipping.

DEBUG: return value for "python setup.py build" is 0 ---->build with python2.7, no errors
Traceback (most recent call last):
  File "setup.py", line 57, in <module>
    pefile_version = _read_attr('__version__')
  File "setup.py", line 39, in _read_attr
    match = re.search(regex, f.read())
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 208687: ordinal not in range(128)
DEBUG: return value for "python3.4 setup.py build" is 1   --->error`
I can't fix this unicode error unfortunately. I am using linux.

**Comment by techtonik** [comment]
Have you tried Python 3.5?

https://travis-ci.org/erocarrera/pefile/jobs/123192709

**Comment by techtonik** [comment]
Can't confirm this on Linux. Attach exact version of pefile.py here, exact version of Linux and Python.

**Comment by ibrahimkaraguzel** [comment]
Hello dude
I am developer at PisiLinux (www.pisilinux.org)
I downloaded this package of yours: https://github.com/erocarrera/pefile/archive/v2016.3.28.tar.gz
My Linux version is 4.1.19
My python3 version is 3.4.3

**Comment by ibrahimkaraguzel** [comment]
Traceback (most recent call last):
  File "setup.py", line 57, in <module>
    pefile_version = _read_attr('__version__')
  File "setup.py", line 39, in _read_attr
    match = re.search(regex, f.read())
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 208687: ordinal not in range(128)

**Comment by techtonik** [comment]
Try this one - https://github.com/erocarrera/pefile/archive/master.zip

**Comment by ibrahimkaraguzel** [comment]
unfortunately same error, and i've used python 3.5

DEBUG: return value for "python setup.py build" is 0
Traceback (most recent call last):
  File "setup.py", line 57, in <module>
    pefile_version = _read_attr('__version__')
  File "setup.py", line 39, in _read_attr
    match = re.search(regex, f.read())
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 208795: ordinal not in range(128)
DEBUG: return value for "python3 setup.py build" is 1

**Comment by slimjim2234** [comment]
same issue here

**Comment by AndCycle** [comment]
got similar issue here, 
I am under traditional chinese ver. win32 so it complain at codepage cp950

```
(env) D:\AndCycle\Documents\work\corelight\proj\leadcheck3\trunk_dep\pyinstaller>pip install pefile
Collecting pefile
  Downloading pefile-2016.3.28.tar.gz (58kB)
    100% |████████████████████████████████| 61kB 770kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\CHIH-H~1\AppData\Local\Temp\pip-build-6zur9qz_\pefile\setup.py", line 57, in <module>
        pefile_version = _read_attr('__version__')
      File "C:\Users\CHIH-H~1\AppData\Local\Temp\pip-build-6zur9qz_\pefile\setup.py", line 39, in _read_attr
        match = re.search(regex, f.read())
    UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 208687: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\CHIH-H~1\AppData\Local\Temp\pip-build-6zur9qz_\pefile\

(env) D:\AndCycle\Documents\work\corelight\proj\leadcheck3\trunk_dep\pyinstaller>
```

**Comment by AndCycle** [comment]
https://github.com/erocarrera/pefile/blob/master/pefile.py#L5308

ok, python actually complain about this line, which have a 
`’`
in it, and it doesn't like it.

**Comment by ibrahimkaraguzel** [comment]
@AndCycle dude, your solution works! Thanks a lot :)

**Comment by slimjim2234** [comment]
I can also confirm this fix works.
When you get time, could you merge @AndCycle changes?
Thanks man

**Comment by joelpx** [comment]
It works for me too.

**Comment by erocarrera** [comment]
Merged @AndCycle's pull request.

**Comment by yan12125** [comment]
Got here from PyInstaller (pyinstaller/pyinstaller#2019). I have to install the latest git-master:
```
python.exe -m pip install https://github.com/erocarrera/pefile/archive/master.zip
```
Looking forward to a new release. Any schedule?

Tested on Windows 7 x86 + Python 3.5.2, codepage 950 (Traditional Chinese)

**Comment by sfulani** [comment]
How did AndCycle resolved the issue. I did not understand... Please hep....
