### ISSUE TITLE
Public travis test

### ISSUE THREAD

**Issue by Rafiot** [erocarrera/pefile#121]
It would be handy to have access to the files used for the tests case, just make sure there are no problems in the PR.

**Comment by erocarrera** [comment]
Unfortunately some samples are private and others are malware (and some both). Malware (often packed) tends to exercise unusual code-paths and makes for good tests. Exposing those files would probably lead to some issues.

**Comment by RyPeck** [comment]
@erocarrera perhaps a subset could be made public?
