### ISSUE TITLE
dump_dict raises ValueError

### ISSUE THREAD

**Issue by knowmalware** [erocarrera/pefile#130]
``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pefile.py", line 4574, in dump_dict
    dump_dict['DOS_HEADER'] = self.DOS_HEADER.dump_dict()
  File "pefile.py", line 943, in dump_dict
    val = bytes([b for b in val if b != 0])
  File "/home/user/.local/lib/python2.7/site-packages/future/types/newbytes.py", line 108, in __new__
    raise ValueError('bytes must be in range(0, 256)')
ValueError: bytes must be in range(0, 256)
```

**Comment by knowmalware** [comment]
There appear to be two problems with the current dump_dict() code.  First, the Structure class's dump_dict() tries to convert to bytes values that might not be in 0-255 range, as indicated above.  Second, the PE class's dump_dict() calls convert_to_printable() which is not defined.

**Comment by ckennard** [comment]
I also encountered this error. Any fix known yet?

**Comment by nyx0** [comment]
I think this commit https://github.com/erocarrera/pefile/commit/971da4ff74ff6d9ba7ef7790dd6526824629d223#diff-c948f10453930d93b48fd0edbe7fcc2dL1001 is the reason why. (For the dump_dict() method in the Structure class)

**Comment by Lindi16** [comment]
any progress withe the merge?

**Comment by knowmalware** [comment]
this one is my fix 4ee9807

it's in a branch on my fork https://github.com/knowmalware/pefile/tree/fix_dump_dict

still playing around with it, so haven't submitted pull request, but there you go if you want to use it

**Comment by erocarrera** [comment]
How can I reproduce the issue? do you have the SHA256 of a file that triggers it (if in VT) or the file itself?

**Comment by knowmalware** [comment]
c62de4a72361cf1db38ba8c4f59d386f0e1c02f190cf6c8698ae3a14295bcb04

Also, since I filed this issue, the changes made to that code block introduced another bug, I think because of variable scope issues.  Here's a fix (for that one):

```python
@@ -973,7 +973,7 @@ class Structure(object):
                         except exceptions.ValueError as e:
                             val = '0x%-8X [INVALID TIME]' % val
                 else:
-                    val = b([b for b in val if b != 0])
+                    val = b([x for x in val if x != 0])
 
                 dump_dict[key] = {'FileOffset': self.__field_offsets__[key] + self.__file_offset__,
                                   'Offset': self.__field_offsets__[key],
```

**Comment by Tigzy** [comment]
Is it possible to merge the above?

**Comment by knowmalware** [comment]
I just submitted PR #161 that fixes this.

**Comment by erocarrera** [comment]
I no longer can reproduce the original issue with the HEAD of the master branch under Python 2.7 or 3.6. I've made changes to how the string data is handled. Please reopen or file a new issue if I overlooked something.

**Comment by knowmalware** [comment]
@erocarrera Can't figure out how to reopen this; it's still an issue.  The hash I referenced above that is causing this for me can be found either from VirusTotal or from contagiodump as "WEBC2-CLOVER_sample_065E63AFDFA539727F63AF7530B22D2F"
