### ISSUE TITLE
error in pefile

### ISSUE THREAD

**Issue by step8876** [erocarrera/pefile#158]
I am using pefile-2016.3.28
First off, it works great, thank you.
I process a lot of files and I rarely have an issue, but I had this, but I can't reproduce it.
it was one of 55 PE32-DLL or 1 PE32-EXE that had this error, the largest is 4.8 megs with the total size being 27 megs.  I have since sent them through again with no issue, but I thought maybe you would have some insight.  Here is the error.
    pe =  pefile.PE(filename, fast_load=True)
  File "build\bdist.win32\egg\pefile.py", line 1713, in __init__
    self.__parse__(name, data, fast_load)
  File "build\bdist.win32\egg\pefile.py", line 1767, in __parse__
    self.__data__ = mmap.mmap(self.fileno, 0, access=mmap.ACCESS_READ)
WindowsError: [Error 8] Not enough storage is available to process this command

looking at google it appears maybe memory leak
http://stackoverflow.com/questions/34609389/python-mmap-modules-offset-argument-exception

but I am not familiar enough with this, so any insight would be helpful.

**Comment by erocarrera** [comment]
Without having an easy way to reproduce it, it won't be easy to know whether it's fixed but, following the indications in stackoverflow, the mmap object will be deleted in the close() method.

**Comment by step8876** [comment]
Hi 
I was able to reproduce this.. the exe in question is 1.95 gigs.. 
not sure if anything can be done for file this size :)

**Comment by step8876** [comment]
guess one follow up is there a way to determine if a file is too big?
