### ISSUE TITLE
SyntaxError in peutils.py

### ISSUE THREAD

**Issue by timoaeb** [erocarrera/pefile#159]
Hello,

It seems that the recently merged commit a9151d6cf1d57c11dd8dc9110a6063a71bc92372 introduces a SyntaxError (repetition of the `:` character) : 
```
        # Helper function to parse the signature bytes
        #
        def to_byte(value) :
            if '?' in value::
                return value
            return int (value, 16)
```
at https://github.com/erocarrera/pefile/blob/465b2eef7f39442e755f9e72b84d65a1bad9f1ff/peutils.py#L429

**Comment by bernhl** [comment]
This was fixed here https://github.com/erocarrera/pefile/commit/475b68dfb4eea4395b623126d60edefd786f6657#diff-81e5430c48902e2a8095bbea02bd0d90L429
