### ISSUE TITLE
what does the function  pefile.PE.write indeed do?

### ISSUE THREAD

**Issue by hugoasdf** [erocarrera/pefile#177]
bellow python code:

```
pe_target = pefile.PE("a.dll")
pe_target.DIRECTORY_ENTRY_IMPORT ={}
pe_target.write(filename='d.dll') 

```

but when use depency walker watch "d.dll" ,the import table of it is not empty,so what can be done with pefile.PE?
look forward the answer.

**Comment by erocarrera** [comment]
"DIRECTORY_ENTRY_IMPORT" is simply an alias. One could do what you want by zeroing the fields (beware that it's a hierarchical set of structures).

This should work:

for entry in pe.DIRECTORY_ENTRY_IMPORT:
    entry.struct.Characteristics = 0
    entry.struct.TimeDateStamp = 0
    entry.struct.ForwarderChain = 0
    entry.struct.Name = 0
    entry.struct.FirstThunk = 0

That will set all the import entries, one per DLL to zero. You can then write the results and the import descriptors should be gone. Note that the import tables will still be somewhere in the file, unreferenced now.
