### ISSUE TITLE
Use of counter creates significant performance hit

### ISSUE THREAD

**Issue by xoviat** [erocarrera/pefile#182]
https://github.com/erocarrera/pefile/blob/master/pefile.py#L1833

![image](https://cloud.githubusercontent.com/assets/15351036/25810577/2137b414-33d6-11e7-9edd-b980aa58bda3.png)

Profiling the code reveals that most if not all of the time spent in this library is on that check. Is that really necessary?

**Comment by bernhl** [comment]
@xoviat are you using pypi? Also, can you please share the executable you used for your benchmark?

**Comment by xoviat** [comment]
No, I attempted to use HEAD for the pyinstaller tests and there was a significant performance hit. I then used pytest-profiling to determine the cause.

**Comment by xoviat** [comment]
@bernhl I already have a PR that I know addresses the issue. Is there anything wrong with that PR? I will need to test the performance of your solution, which may not work correctly.

**Comment by bernhl** [comment]
Your PR is fine, I just try to figure why and under which circumstances collections.Counter causes this performance hit.

**Comment by xoviat** [comment]
Also, out of curiousity, do you have any contact with the author of this package to get these merged?

**Comment by erocarrera** [comment]
Just did, will do a release ASAP. Apologies for the horrible, horrible delay.
