### ISSUE TITLE
Regression in dump_dict

### ISSUE THREAD

**Issue by theavgjojo** [erocarrera/pefile#185]
At some point, an error was introduced in dump_dict():
https://github.com/erocarrera/pefile/blob/master/pefile.py#L991

Correct code:
`val = bytes([b for b in val if b != 0])`

Incorrect code in the latest master:
`val = b([b for b in val if b != 0])`

**Comment by bernhl** [comment]
This was fixed here https://github.com/erocarrera/pefile/commit/3033d5397ce7030136445ed5e057867c78973948#diff-c948f10453930d93b48fd0edbe7fcc2dL991
