### ISSUE TITLE
TypeError: unorderable types: NoneType() >= int() in parse_export_directory

### ISSUE THREAD

**Issue by sebdraven** [erocarrera/pefile#191]
The problem is in parse_export_directory:

if symbol_address is NoneType and max_failed_entries_before_giving_up > 0, the test symbol_address >= rva and symbol_address < rva+size is executed and this exception is thrown.

The test symbol_address is not None must be added.
#190

**Comment by erocarrera** [comment]
Merged #190, closing issue.
