### ISSUE TITLE
Please push releases to PyPI

### ISSUE THREAD

**Issue by htgoebel** [erocarrera/pefile#193]
https://pypi.python.org/pypi/pefile still points to release 2016.3.28, while there is 2017.5.26 for quite some time now.

**Comment by htgoebel** [comment]
Needed for https://github.com/pyinstaller/pyinstaller/issues/1920

**Comment by techtonik** [comment]
https://pypi.python.org/pypi/pefile/2017.8.1 ?

**Comment by htgoebel** [comment]
IC.
