### ISSUE TITLE
kernel patching possible?

### ISSUE THREAD

**Issue by toddfraser88** [erocarrera/pefile#196]
over at MSFN forums we've been trying to make an XP equivalent of kernelex using some of xeno86's old code without much success 
- it adds a new section rather than adding to an existing one

can this c++ code convert to python?
[kernelxp.zip](https://github.com/erocarrera/pefile/files/1115551/kernelxp.zip)

**Comment by mrexodia** [comment]
There appears to be no code related to PE or adding a section here...

**Comment by erocarrera** [comment]
It is possible but there are few convenience methods for it. One may need to move things around to make room for any structures that don't fit, i.e. if there's no room for the new section's structure, you'll need to move things around and update all the relevant offsets.
