### ISSUE TITLE
Garbage values for `e_res2` and `e_res` in DOS_HEADER

### ISSUE THREAD

**Issue by boddumanohar** [erocarrera/pefile#198]
I am getting garbage values in two ways:

Method 1: copy `ordlookup`, `pefile` and `peutils` to the sample folder and `import pefile`

When I tried to dump_json() DOS_HEADER values, I am getting garbage values like `\\x00\\x00\\x00\\x00\\x00\\x00` for values of  `e_res2` and `e_res` of DOS_HEADER. 

Here is the example paste for output : https://pastebin.com/5PB05mdP

Method 2: pip3 install pefile and `import pefile`

Since pefile pip version doesnt have dump_dict() function for Sturcture class, I ve extended Structure to add dump_dict() function. 

When I tried to dump_json() DOS_HEADER values, I am getting garbage values like `b''` for the values of `e_res2` and `e_res` of DOS_HEADER where an integer (uint_32) is expected.

Here is the example paste for output : https://pastebin.com/yu5Qvvwi

**Comment by bernhl** [comment]
The issue seem to be that e_res and e_res2 are defined as `'8s,e_res', ..., '20s,e_res2',` instead of `'4H,e_res', ..., '10H,e_res2'`
https://github.com/erocarrera/pefile/blob/a765f497306227294cf2ff5337d24f261dda2212/pefile.py#L1539

**Comment by boddumanohar** [comment]
`b''` are because python3 differentiates between byte literal and string literal. refer this stackoverflow issue. https://stackoverflow.com/a/6269785
