### ISSUE TITLE
Add option to disable malformation detection without the need to manually call full_load()

### ISSUE THREAD

**Issue by sebtoun** [erocarrera/pefile#211]
On big executable (typically installers of hundreds megabytes), PE `__init__` method can be very slow (>30 seconds). After profiling it appears that this is caused by the detection of possible malformations (the counting each byte occurence through the whole file).

Using `fast_load=True` disable this detection but also the parsing of usefull informations, hence the need to manually call `full_load` after PE object creation. It could be handy (and maybe clearer) to have a dedicated options to disable such detection.

For comparison, the whole duration of PE creation using `fast_load=True` followed by a call to `full_load` is less than half a second while the duration of PE creation without `fast_load` is > 30 seconds.

An alternative would be to only disable malformation detection when `fast_load=True`.

**Comment by erocarrera** [comment]
That is a very reasonable request. I'm thinking I'll add an keyword argument such as "enable_heuristics", set to True by default, that controls that, so you can disable it and get faster load times.

**Comment by sebtoun** [comment]
I would gladly make a PR, but I can't run regression tests.

**Comment by erocarrera** [comment]
The fix to issue #182 already provides with the alternative mechanism suggested. If the PE is parsed with "fast_load=True" and then full_load() is called, the malformation checks are skipped.
