### ISSUE TITLE
Open handle to file on windows prevents write to file after opening with pefile

### ISSUE THREAD

**Issue by kfilbrun** [erocarrera/pefile#214]
Running on windows, following init of a pefile object:

`pe = pefile.PE(filename)`

I can no longer open 'filename' for binary write. However, I can on Debian. I was able to get around the issue by reading the data in myself and then passing it in directly to the constructor. I believe the problem is that the memory mapped file handle is not closed correctly, but I didn't hunt it down completely.

**Comment by erocarrera** [comment]
Hi, likely, pefile does not  automatically close the handle as it may be needed for further parsing. You can call the close() methods in your pefile.PE instance. That should solve the issue. Let me know if it wouldn't.
