### ISSUE TITLE
PEFile

### ISSUE THREAD

**Issue by prabhumanis** [erocarrera/pefile#235]
PEFILE module is not working properly in Python 3.6

import pefile
pe=pefile.PE("D:\\strings.exe")
print(pe.OPTIONAL_HEADER.AddressOfEntryPoint)

error msg:

 pe=pefile.PE("D:\\samples\\specialsearch\\test\\strings.exe")
AttributeError: module 'pefile' has no attribute 'PE'

**Comment by bernhl** [comment]
I just tested with python3.6 and cannot reproduce the issue. Can you please write a script provoking the issue and attach it as file? Also, which version of pefile are you using?

**Comment by prabhumanis** [comment]
[check.txt](https://github.com/erocarrera/pefile/files/2245976/check.txt)
*source code*
import os
import pefile
pe=pefile.PE("D:\\\test\\strings.exe")
print ("PE Signature: " + hex("D:\\test\\strings.exe"))
print (hex(pe.VS_VERSIONINFO.Length))
print(pe.OPTIONAL_HEADER.AddressOfEntryPoint)

After run the above mentioned script, i got below mentioned error
**Error message**
Traceback (most recent call last):
  File "C:\Python\Python36-32\check.py", line 3, in <module>
    pe=pefile.PE("D:\\\test\\strings.exe")
AttributeError: module 'pefile' has no attribute 'PE'

PE file version 

__author__ = 'Ero Carrera'
__version__ = '2017.12.16'
__contact__ = 'ero.carrera@gmail.com'

PY3 = sys.version_info > (3,)

please find the PE file module attachment
[pe.zip](https://github.com/erocarrera/pefile/files/2246026/pe.zip)
i uploaded few files from pe file module,Due to file size i cant upload full PE file module

please let me know if you need any other assistance

**Comment by erocarrera** [comment]
My guess is that there is some file in your directory or python path, named pefile.py, and that's what's being imported, instead of the pefile module.
