### ISSUE TITLE
VS_FIXEDFILEINFO object has changed structure

### ISSUE THREAD

**Issue by kalibyrn** [erocarrera/pefile#236]
The VS_FIXEDFILEINFO object appears to have changed structure, and therefore breaks some existing scripts when the try to access the Signature property.

    import pefile
    pef = pefile.PE('sample_file')
    print('{}'.format(pef.VS_FIXEDFILEINFO.Signature))

This throws:

    Traceback (most recent call last):
      File "y.py", line 3, in <module>
        print('{}'.format(pef.VS_FIXEDFILEINFO.Signature))
    AttributeError: 'list' object has no attribute 'Signature'

This didn't appear to happen in 2017.11.5

**Comment by CrimsonGlory** [comment]
Same happens with VS_VERSIONINFO

```
 res["version_info"] = {'Length': pelib.VS_VERSIONINFO.Length,
 AttributeError: 'list' object has no attribute 'Length'
```
