### ISSUE TITLE
Licence inconsitency - MIT or proprietary?

### ISSUE THREAD

**Issue by htgoebel** [erocarrera/pefile#251]
I was pointed out by the FSF that pefile is licensed ambiguously:
- https://pypi.org/project/pefile/ states it is licensed under the MIT license
- the archive contains a copy of MIT license,
- but `pefile.py` states a different terms, namely, "All rights reserved".

The FSF takes this as ["in other words, it's proprietary."](https://savannah.gnu.org/task/?15146#comment1)

Please change the licence header in all relevant files to state it is MIT licensed. Thanks.

**Comment by erocarrera** [comment]
Thanks for letting me know! I just pushed a change to address this and it will be pushed out in the next release.

**Comment by htgoebel** [comment]
Thanks for fixing :-)
