### ISSUE TITLE
Wrong definition of __CV_INFO_PDB70_format__  in PE.parse_debug_directory function

### ISSUE THREAD

**Issue by gratuitochou** [erocarrera/pefile#252]
`                    # pdb7.0
                    __CV_INFO_PDB70_format__ = ['CV_INFO_PDB70',
                        ['I,CvSignature',
                         'I,Signature_Data1', # Signature is of GUID type
                         'H,Signature_Data2',
                         'H,Signature_Data3',
                         'H,Signature_Data4',
                         'H,Signature_Data5',
                         'I,Signature_Data6',
                         'I,Age']]
`

The definition of GUID is split into six parts and the last one 'Signature_Data6' is defined as unsigned  int. But according to the Windows SDK file <guiddef.h> the "GUID" is defined as:
`
#ifndef GUID_DEFINED
#define GUID_DEFINED
#if defined(__midl)
typedef struct {
    unsigned long  Data1;
    unsigned short Data2;
    unsigned short Data3;
    byte           Data4[ 8 ];
} GUID;
#else
typedef struct _GUID {
    unsigned long  Data1;
    unsigned short Data2;
    unsigned short Data3;
    unsigned char  Data4[ 8 ];
} GUID;
#endif
#endif
`
So the last 8 byte is actually a byte array not an integer. When I parse a dll file, pefile gives me :
![pefile](https://user-images.githubusercontent.com/12407079/51101416-85d1a680-1815-11e9-8e29-cb3141a36c89.png)

and visual studio gives me:
![vs](https://user-images.githubusercontent.com/12407079/51101441-9eda5780-1815-11e9-8bd2-b93e4b29093a.png)

pefile reversed the last 8 byte cause it treat the array as an integer.

**Comment by erocarrera** [comment]
Thanks! Commit d88e144 improved handling of the GUID.
