### ISSUE TITLE
Delay Load Directory version 1 is not parsed properly

### ISSUE THREAD

**Issue by ladislav-zezula** [erocarrera/pefile#302]
**Sample:** e8d3bff0c1a9a6955993f7a441121a2692261421e82fdfadaaded45d3bea9980

**Problem:** Loading sample with `pefile.PE(file_name, fast_load = False)` takes huge amount of time

**Reason:** The image has delayed imports. The first entry in the import descriptor list is:
```
IMAGE_DELAY_LOAD_DESCRIPTOR
  Attributes = 0x00000000
  NameRva = 0x006f5208
  ModuleHandleRva = 0x00000000
  DelayImportAddressTableRva = 0x006f50c0
  DelayImportNameTableRva = 0x006f511c
  BoundDelayImportTableRva = 0x006f5178
  UnloadDelayImportTableRva = 0x006f51c0
  TimeStamp = 0x00000000
```
The value of "Attributes = 0" means that this is Microsoft Delayed Import Descriptor version 1.0 (the old one, created by Visual Studio 5.0 or so). In that case, the RVAs in the structure are not really RVAs, but actually VAs (direct pointers into the EXE). The pelib library does not reflect that and reads from them as if they were RVAs. As consequence, it reads an array of functions from different offsets and reads A LOT of them (the file has 15 MB).

Another variant of Microsoft Delay Load Descriptor is Attributes = 0x01, when RVAs are actually RVAs.

[e8d3bff0c1a9a6955993f7a441121a2692261421e82fdfadaaded45d3bea9980.zip](https://github.com/erocarrera/pefile/files/5588197/e8d3bff0c1a9a6955993f7a441121a2692261421e82fdfadaaded45d3bea9980.zip)

**Comment by erocarrera** [comment]
I merged #304 , thanks so much!
