### ISSUE TITLE
Bug: IndexError when dumping FileInfo

### ISSUE THREAD

**Issue by pd-fkie** [erocarrera/pefile#313]
In PE.dump_dict on [line 5051](https://github.com/erocarrera/pefile/blob/e7a2d9f40bda10c8a94d424b184b287151a53993/pefile.py#L5051) the FileInfo array is accessed without checking if the index is valid.

The affected code:
```py
if hasattr(self, 'FileInfo'):
    for entry in self.FileInfo[idx]:
```

With the file given below `FileInfo` is an empty array resulting in an IndexError on the last line.
In PE.dump_info on [line 4744](https://github.com/erocarrera/pefile/blob/e7a2d9f40bda10c8a94d424b184b287151a53993/pefile.py#L4744) this check is already present:
```py
if hasattr(self, 'FileInfo') and len(self.FileInfo) > idx:
    for entry in self.FileInfo[idx]:
```
Exception:
```
Traceback (most recent call last):
  File "fuzz_pefile.py", line 12, in test_one_input
    p.dump_dict()
  File "pefile.py", line 5051, in dump_dict
    for entry in self.FileInfo[idx]:
IndexError: list index out of range

```

---

Crash file: [crash-e9fa4577414ec8f97511ef2f7a12794401e7cd22](https://github.com/pd-fkie/crashes/raw/main/crash-e9fa4577414ec8f97511ef2f7a12794401e7cd22)

**Comment by erocarrera** [comment]
Thanks for reporting!
