### ISSUE TITLE
Bug: IndexError when relocating image

### ISSUE THREAD

**Issue by pd-fkie** [erocarrera/pefile#314]
In PE.relocate_image on [line 5484](https://github.com/erocarrera/pefile/blob/e7a2d9f40bda10c8a94d424b184b287151a53993/pefile.py#L5484) the sixth element of the Optional Header Data Directories is accessed but when parsing the file given below
the list of data directories is empty resulting in an IndexError.

Affected code:
```py
if self.OPTIONAL_HEADER.DATA_DIRECTORY[5].Size:
```

Exception:
```
Traceback (most recent call last):
  File "fuzz_pefile.py", line 21, in test_one_input
    p.relocate_image(0x40000)
  File "pefile.py", line 5484, in relocate_image
    if self.OPTIONAL_HEADER.DATA_DIRECTORY[5].Size:
IndexError: list index out of range
```

---
Crash file: [crash-8499a0bb33aeba8f59a172584abc7ca0ab82a78c](https://github.com/pd-fkie/crashes/raw/main/crash-8499a0bb33aeba8f59a172584abc7ca0ab82a78c)

**Comment by erocarrera** [comment]
Thanks for reporting!
