### ISSUE TITLE
pefile 2021.5.13 is_driver() behavior changed from previous version

### ISSUE THREAD

**Issue by joachimmetz** [erocarrera/pefile#322]
Not sure if this a regression issue or new behavior. For Plaso (https://github.com/log2timeline/plaso) we use pefile and have a unittest that runs on a driver test file https://github.com/log2timeline/plaso/blob/main/test_data/test_driver.sys

In previous versions of pefile `is_driver()` returned True however with pefile version 2021.5.13 this no longer seems the case. I'll update the tests and version of pefile for now, since distros appear to be rolling this out this version. 

But hope you have more insight to see if this is regression or new behavior.

Also tracking this in https://github.com/log2timeline/plaso/issues/3591

**Comment by joachimmetz** [comment]
Is possible that this PR is related https://github.com/erocarrera/pefile/pull/320

**Comment by erocarrera** [comment]
Hi Joachim! Will take a look asap and also add that file to my unittests.

**Comment by joachimmetz** [comment]
@erocarrera thx much appreciated

**Comment by erocarrera** [comment]
Fixed in v2021.5.24
