### ISSUE TITLE
doesn't change resource content

### ISSUE THREAD

**Issue by s0i37** [erocarrera/pefile#326]
Hello.
I am trying to change content into resource directory
```
pe = pefile.PE("mimikatz.exe")
pe.set_bytes_at_rva(0x000e5417, b'\xff')   # will change
pe.set_bytes_at_rva(0x000e5418, b'\xff')   # will NOT change (why?!)
pe.write("mimikatz.exe")
```
But some regions doesn't change.

**Comment by erocarrera** [comment]
Hi, can you provide the executable or its hash? It may come handy to help debug the issue.

**Comment by s0i37** [comment]
Sure. It is d3799afb20d176652aa74a839716af35
It seems that pefile changes only data outside of resource content.

**Comment by erocarrera** [comment]
I admit this is a bit counter intuitive but the `write` method will first apply all changes you've made via `set_bytes` and similar methods, and then will write all strings contained in the convenience structures for `VS_VERSIONINFO`. 
In this case the latter step are overwriting your second `pe.set_bytes_at_rva` at 0x000e5418. That is where the value of `OriginalFilename` is stored, which is `mimikatz.exe`.

If what you want is to change the name, you can do it via:

`pe.FileInfo[0][0].StringTable[0].entries[b'OriginalFilename'] = b'yourkatz.exe'`

and then do a `pe.write`. That should update the `OriginalFilename` value. Beware that pefile won't relayout the PE for you, if the new string you write does not fit and runs into another string, that won't look pretty.

**Comment by s0i37** [comment]
Just `pe.FileInfo=[]` is solve.

**Comment by s0i37** [comment]
And the same for overlay.
Can I change overlay with `pefile` ?

**Comment by erocarrera** [comment]
Unless you need to update some fields in the PE headers to point to data in the overlay, I'd guess you can just append the data to the file and write it using basic Python filesystem I/O functionality.
