### ISSUE TITLE
Bytes in Data Dict

### ISSUE THREAD

**Issue by hacktorious** [erocarrera/pefile#330]
I'm attempting to call pefile.PE(path_to_file) then pe.dump_dict().  This produces a data dictionary which cannot be converted to JSON via json.dumps().  For some reason the data dict has bytes inside of it.  This is with any random MS dll file.

The dictionary looks something like this:
{
    "greeting": b "hello world"
}

Any suggestions?

**Comment by hacktorious** [comment]
So is it possible to pass the results as a JSON via a web call without having to parse the entire file and convert to base64?

**Comment by erocarrera** [comment]
I can't think of an easy way other than that, just recursively processing the whole dictionary returned by `dump_dict()` and convert any `bytes` to a unicode `str` or base64, whatever suits your application.

I quickly wrote this function to recursively go through every object and convert any `bytes` to a `utf-8` `str`:

```python
def do_obj(obj):
    if isinstance(obj, dict):
        d = dict()
        for k, v in obj.items():
            d[do_obj(k)] = do_obj(v)
        return d
    elif isinstance(obj, (list, tuple)):
        l = list()
        for item in obj:
            l.append(do_obj(item))
        if isinstance(obj, tuple):
            return tuple(l)
        return l
    elif isinstance(obj, bytes):
        return obj.decode('utf-8')
    elif isinstance(obj, (str, int, float)):
        return obj
    else:
        raise Exception(f'Unexpected[{obj}]')
```

Passing the returned dictionary to `json.dumps()` no longer fails. Something along the lines may suit your purpose.

**Comment by hacktorious** [comment]
Thanks,  an easier way that worked for me was to create a JSON encoder.
 Only one line of code.
