### ISSUE TITLE
Incapable of dumping independent swf files with index

### ISSUE THREAD

**Issue by z0xyz** [erocarrera/pefile#337]
Is there a way to extract each swf file embedded within the raw data with its accompanying index number .

**Comment by erocarrera** [comment]
Hi, there isn't much information to understand what's the exact issue you're having. 
If there is some sort of content within a PE file it should be possible to extract it it is referenced via the PE structures (is it a resource, or maybe an overlay?). 
If the content you refer to is enclosed in some data section and used by the application, it may be harder. If it's not compressed or encoded it should be possible to look for SWF headers and dump from those offsets; I imagine the SWF file's headers may contain a size field that would help know how much to dump out, but I haven't looked into the format.

**Comment by z0xyz** [comment]
The PE [file](https://www.mediafire.com/file/n4ajopgvvq7i7b4/Section1.exe/file) is an executable flash projector that has multiple .swf file compiled within it , and i was trying extract the embeddedf raw data i.e. .swf files. I did manage to extract them with multiple scripts and full-fledged tools e.g. jpexs-decompiler , however one problem is that i can't extract them with the exact reference with in the flash projector

**Comment by erocarrera** [comment]
I'm unsure on how the issue you describe could be helped with pefile. It doesn't sound to me like the data you want to extract would be "reachable" via the PE format's structures.

**Comment by z0xyz** [comment]
I've used the pefile before to grab the embedded textual content of the raw swf files from within the pe file before (which was closest i can get) , however due to my unawareness of the pe file structure i thought you could help me to realize what i'm actually looking for higher level of abstraction (namely the respective index attribute of each swf file within pe file) using this library .

**Comment by erocarrera** [comment]
I've taken a quick look and it's not obvious to me that the SWF would be reachable via the PE resources, most likely they are embedded in the file following a structure known to the application. Actually, the reported total size (SizeOfRawData) of all the sections in the PE is 781824 bytes. While the file is over 20MB in size, so there's definitely data outside what's described by the PE headers.
I'd simply scan for the signature of SWF files, make some sanity checks, and read off the `unit32` value corresponding to the SWF's header `FileLength` field. If it's a reasonable file length I'd dump that and hope for the data to be well-formed.

**Comment by z0xyz** [comment]
i'm currently unaware of such low-level intricates , and that's why i resorted to the library .
however i don't know if that might helps in narrowing down the solution .
I've used the get_overlay method on the exe file , and after inspecting the resulting file with `bvi` i was able to identify each `index=""` string , but that wasn't particularly helpful as they were accompanied with the 'text' contained within each 'swf' file rather than the adjacent bytes of the respective 'swf' file .
```
import sys
import pefile

filename = sys.argv[1]
with open(filename , 'rb') as s :
    r = s.read()

pe = pefile.PE(filename)

offset = pe.get_overlay_data_start_offset()

with open(filename + ".app" , "wb") as t :
    t.write(r[offset:])
```

**Comment by erocarrera** [comment]
The task you are attempting is that of dumping embedded contents. I have a hunch that something like what I suggested above might work (find signatures, parse file lengths, and dump). 
All this is however unrelated to `pefile` as is does not relate to the PE format or parsing its contents. There are probable better forums what may help you towards your goals.
