### ISSUE TITLE
write() does not work.

### ISSUE THREAD

**Issue by zanemendoza123** [erocarrera/pefile#357]
I compiled this code in Visual Studio.
```cpp
#include <iostream>

int main()
{
    std::cout << "Hello World!\n";
}
```
Then wanted to use pefile to add some file properties ("File Description, "Copyright", etc.)
```python
>>> import pefile
>>> pe = pefile.PE("C:\\bin\\HelloWorld.exe")
>>> pe.FileInfo[0][0].StringTable[0].entries[b'FileDescription'] = b'Hello World'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'PE' object has no attribute 'FileInfo'. Did you mean: 'fileno'?
```
The error says my binary doesn't have the attribute `FileInfo` so I used another PE (`notepad.exe`) and copy its `FileInfo` and added it as an attribute to the original binary (`HelloWorld.exe`). 
```python
>>> pe_src = pefile.PE("C:\\Windows\\System32\\notepad.exe")
>>> setattr(pe, "FileInfo", pe_src.FileInfo)
```
Now I can edit the binary's `FileDescription` and verify that the modification is successful.
```python
>>> pe.FileInfo[0][0].StringTable[0].entries[b'FileDescription'] = b'Hello World'
>>> print(pe.FileInfo[0][0].StringTable[0].entries[b'FileDescription'])
b'Hello World'
```
However, when I used the `write()` command, the changes was not reflected. Based on the error, it seems like the `FileInfo` attribute was not written.
```python
>>> pe.write("C:\\bin\\NewHelloWorld.exe")
>>> pe_new = pefile.PE("C:\\bin\\NewHelloWorld.exe")
>>> print(pe_new.FileInfo[0][0].StringTable[0].entries[b'FileDescription'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'PE' object has no attribute 'FileInfo'. Did you mean: 'fileno'?

```

**Comment by erocarrera** [comment]
Hello, this is working as intended, which unfortunately will not solve your issue.
`pefile`'s `write()` method is intended to change existing values. While it can be used to add new structures to an existing PE file, it does require that one does all the housekeeping of pointing to it from any parent structures. In the case of  `FileInfo`, it needs to be described from the corresponding entry in the resources directory. 
If you manage to compile a PE file with resources and the `FileInfo` data, you would be able to modify it with `pefile` but then I guess you'd no longer need to.
