### ISSUE TITLE
Any plans for python 3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pefile#36]
```

Are there any plans to port this to python 3?
There aren't any good python 3 pe parsers out there, so this will be a great 
help

```

Original issue reported on code.google.com by `simonz...@gmail.com` on 18 Jan 2012 at 12:09

**Comment by jhg-tgu** [comment]
```python
Running setup.py (path:/home/jesus/PyEnv/Tuckoo/build/pefile/setup.py) egg_info for package pefile
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/jesus/PyEnv/Tuckoo/build/pefile/setup.py", line 5
        except ImportError, excp:
```

**Comment by rr-** [comment]
Same

**Comment by phaethon** [comment]
The same here. Cannot use this currently within a python3 project.

**Comment by epu** [comment]
Am porting my work to python3, pe is a holdout. I will install a fork, but it would be nice to use the official repo.

**Comment by obestwalter** [comment]
:+1: I will start using the fork for now as well, as we're porting our Systems to python3. pefile is the last dependency that is not yet (officially) ported.

**Comment by RyPeck** [comment]
@epu and @obestwalter which fork are you using?

**Comment by epu** [comment]
I am using the pull-request for python 3 support (branch/commitid https://github.com/erocarrera/pefile/pull/69 <https://github.com/erocarrera/pefile/pull/69>)

But I haven't finished my 2to3 and unit test fixes, so I can't speak to quality yet.
But it does install into my virtualenvs ok.

-e

**Comment by obestwalter** [comment]
@RyPeck If I am not mistaken this one is the most promising: https://github.com/esnesenon/pefile the pull request @epu refers to is made from that. According to [this note](https://github.com/esnesenon/pefile/commit/b4ad35d5f2f324d5b1ca593020950eff9de5d371) it is compatible with 2.7 and 3.4.

Ir would be nice to hear from @erocarrera if there is a chance that this will be merged.

**Comment by obestwalter** [comment]
The fork definitely needs some work still . I just found at least one problem in Structure class where a float is passed as file offset. Will try to fix that and then do a PR against the fork.

**Comment by obestwalter** [comment]
@esnesenon I started a [PR](https://github.com/esnesenon/pefile/pull/2) against your fork and will update it during the next days while running my (very limited) tests against it. If we get something consistent this could be merged here, if @erocarrera gives the green light.

**Comment by obestwalter** [comment]
I ran into more problems creating a new pe object from a changed file to do with data in Structure.__unpack__ not being of expected type bytes and then having the wrong length if encoded in utf8 (69 instead of expected 64). The test fails under Python3 and succeeds under Python2. I will investigate further.

**Comment by esnesenon** [comment]
Hey Oliver,

Thanks for the work and fixes. Could you upload a test case for this issue?
I would like to investigate as well if you're not finished yet.

Will merge the PR once I get an OK from you about this issue.

Cheers,
Shay

On Tue, Dec 29, 2015 at 8:57 PM, Oliver Bestwalter <notifications@github.com

**Comment by obestwalter** [comment]
@esnesenon At this moment the PR only contains one obvious and safe change (aliassing long on Py3). I will try to sort out the other issue tomorrow and add some tests. Are you using your fork with Python3 already?

**Comment by obestwalter** [comment]
o.k. after some more testing and looking at the code I think it's better to wait for @erocarrera to give his opinion first on how he wants to procede. I don't even know if it's a good idea to try to support more than one Python Version with this codebase. This is mainly a research tool and as that it is already doing a very good job. There are no automated tests and I saw a lot of places in the code where exceptions are completely swallowed and other things that make debugging and testing the codebase not particularly easy. On the other hand: the existing code is very stable and has not had very many changes in the recent past. It might be sensible to just have an independent Python3 fork. I don't use pefile as a research tool - I just need it to perform some very specific tasks to tamper with some binaries for our internal tests as part of build finalizazion and I don't even know how many people use it for things like that.

**Comment by erocarrera** [comment]
The latest version of pefile works both with Python 2.7 and Python 3.

**Comment by obestwalter** [comment]
Great! I just realized also that you added automatic testing already last summer. I missed that because I checked out the py3 fork and wrongly assumed that it was in sync with the latest code from this repository.

**Comment by zganger** [comment]
@RyPeck appears you've already been investigating this
