### ISSUE TITLE
Perform new release

### ISSUE THREAD

**Issue by Javagedes** [erocarrera/pefile#364]
a CodeQL / Vulnerability scan detected a vulnerability by one of our downstream users (https://github.com/tianocore/edk2-pytool-extensions/issues/430) due pefile's use of the `future` package. We see that you had already removed `future` as a dependency in #348 for other reasons. 

Would you be able / willing to do a new release to pypi so that we can take those changes without needing to pip install from the github repository directly?

Thanks!!

**Comment by erocarrera** [comment]
Working on it. Making a release soon.

**Comment by erocarrera** [comment]
This is now out as [release 2023.2.7](https://github.com/erocarrera/pefile/releases/tag/v2023.2.7)
