### ISSUE TITLE
find bug in format string at line 4074

### ISSUE THREAD

**Issue by im-overlord04** [erocarrera/pefile#368]
Hello, I've found a little bug (and a typo) in the format string at line 4074/4075:

```
4074 "No pasring available for IMAGE_DYNAMIC_RELOCATION_TABLE.Version = %d",
4075                image_dynamic_reloc_table_struct.Version,
```
I guess that the comma should be replaced with '%' as follows:
```
4074 "No parsing available for IMAGE_DYNAMIC_RELOCATION_TABLE.Version = %d"%
4075                image_dynamic_reloc_table_struct.Version,
```

Is the fix correct?
Thanks for viewing

**Comment by im-overlord04** [comment]
In the same function if it is not possible to unpack `image_dynamic_reloc_table_struct` (line 4061), in the except clause `None` should be returned to avoid several subsequent errors.

**Comment by erocarrera** [comment]
Thank you, good eye! you are correct.
