### ISSUE TITLE
how do for the result of dump in str

### ISSUE THREAD

**Issue by CeContreras** [erocarrera/pefile#376]
![image](https://github.com/erocarrera/pefile/assets/42829956/d106c071-8a43-4ab0-8cec-17110302f1b3)
i am used .dump_info()

**Comment by erocarrera** [comment]
You can find each of those fields and their corresponding value exposed as attributes of the PE instance. 
For the fields that you highlight that would be, assuming your PE instance is named `pe`, `pe.DOS_HEADER.e_magic` and so on.

**Comment by CeContreras** [comment]
![image](https://github.com/erocarrera/pefile/assets/42829956/9fea8e66-3166-4026-b33b-ee5f499f9776)

![image](https://github.com/erocarrera/pefile/assets/42829956/11d2cdd8-438d-40fb-abd7-309fbbd4e187)

I realiced your instruction, however i get number. This means memory address?

**Comment by erocarrera** [comment]
Most of the header values are numbers (some refer to addresses, relative or absolute, and others can be counts, ids, etc). If you just print them you'll see their base-10 representation. `dump_info()` shows their base-16 (hex) representation.
