### ISSUE TITLE
Latest version not available to install through pip

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pefile#48]
```
What steps will reproduce the problem?
1. pip install --upgrade -v -v -v pefile

Installed version (1.2.10-114) is most up-to-date (past versions: 1.2.10-114, 
1.2.10-63, 1.2.10-60, 1.2.10-56, 1.2.9.1, 1.2.9)

What is the expected output? What do you see instead?
I expected the newest version of pefile to be available through pip: 
pefile-1.2.10-139

What version of the product are you using? On what operating system?
Linux, Python 2.7

Please provide any additional information below.


```

Original issue reported on code.google.com by `jamesgst...@gmail.com` on 25 Jun 2014 at 2:52

**Comment by qtfkwk** [comment]
This also affects other project that want to use/depend on pefile! Ideally, I could just put 'pefile' in my 'install_requires' list for setuptools.setup and people installing my module would automatically get pefile installed. This forces me to have users perform a custom installation step to get pefile, or I have to integrate the parts of pefile into my project somehow. Unacceptable! All you have to do is upload the current tarball to PyPI afaik and this will go away.

**Comment by erocarrera** [comment]
This should work now.

**Comment by qtfkwk** [comment]
No, it doesn't work now. Reason is that you have to _upload to PyPI_! For example: `python setup.py sdist bdist_wheel upload`

**Comment by vszakats** [comment]
I confirm it doesn't work. At least now how it did previously. How to install `pefile` with `pip` now?

**Comment by qtfkwk** [comment]
should be: `pip install --allow-external https://github.com/erocarrera/pefile/releases/download/v2016.3.4/pefile-2016.3.4.tar.gz`

**Comment by vszakats** [comment]
Thank you, this however leads to a deprecation warning:
```
python -m pip install --allow-external https://github.com/erocarrera/pefile/releases/download/v2016.3.4/pefile-2016.3.4.tar.gz
DEPRECATION: --allow-external has been deprecated and will be removed in the future. Due to changes in the repository protocol, it no longer has any effect.
You must give at least one requirement to install (see "pip help install")
```

Is there some way to avoid installing from an external source?

**Comment by vszakats** [comment]
Even worse, it's not a warning, but an error and `pefile` is not installed.

**Comment by qtfkwk** [comment]
If @erocarrera simply ran `python setup.py sdist upload`, then the sdist (tgz/zip) would be at pypi and `pip install pefile` would *just work*, along with other things like adding pefile as a dependency in other packages, just like every other well-maintained Python package.

Alternatively, you could also clone the github repo and install directly: `git clone https://github.com/erocarrera/pefile.git; cd pefile; python setup.py install`.

**Comment by vszakats** [comment]
I'm testing the manual method now. It also seems to need `pip install future` in order to work.

Fingers crossed that `sdist` command will be run to avoid all these hacks.

**Comment by erocarrera** [comment]
Hi @qtfkwk , I hope that will work. I've ran that one and a few other commands hoping to solve the issue; but they only update the information at and somehow do not refresh older versions, which remain lingering somewhere in pypi:

https://pypi.python.org/pypi/pefile/ 
(as you can see, now there are packages and everything is up to date)

I may have broken something as I was tweaking many things trying to get pypi to refresh, I've uploaded again the latest release and hopefully that will work.

As far as I understand, the information there is as good as it needs to be. Unfortunately pypi's index appears to not be refreshed (seems it's a general issue, see #92).
If you have some additional information that may help solve the issue I'd love to hear about it.

**Comment by vszakats** [comment]
@erocarrera: Now it seems to be working fine using `pip`. I'll be restoring the old logic and retest.

**Comment by limited-root** [comment]
when i use new pefile version, i get errors simetimes from cuckoo analyzer. one of developer suggested em to use older version of pefile (2013)  but i couldnt install it by sudo python setup.py, can u help me

**Comment by qtfkwk** [comment]
@limited-root how about instead of hijacking this issue for your own, completely unrelated purposes, you create a new issue?
