### ISSUE TITLE
Packed binary causes segmentation fault

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pefile#63]
```
What steps will reproduce the problem?
1. pefile.PE("d761f3aa64064a706a521ba14d0f8741")



What is the expected output? What do you see instead?
Segmentation Fault

What version of the product are you using? On what operating system?
Version:  pefile-1.2.10-139
OS: Ubuntu Linux 64bit, Python 2.7.6 64bit

Does not seg fault on python 2.7.8.10 on Windows 8 64bit python

File is attached.  Password is "infected"
```

Original issue reported on code.google.com by `Allen.Sw...@gmail.com` on 18 Mar 2015 at 5:35

Attachments:
* [d761f3aa64064a706a521ba14d0f8741.7z](https://storage.googleapis.com/google-code-attachments/pefile/issue-63/comment-0/d761f3aa64064a706a521ba14d0f8741.7z)

**Comment by obilodeau** [comment]
No segfault on this file for Ubuntu 64 bit with Python 2.7.8 and pefile 1.2.9.1.
