### ISSUE TITLE
setup.py bdist_rpm fails

### ISSUE THREAD

**Issue by joachimmetz** [erocarrera/pefile#65]
```
python ./setup.py bdist_rpm
Traceback (most recent call last):
  File "./setup.py", line 8, in <module>
    import pefile
  File "/home/user/Projects/wip/pefile-pefile-1.2.10-139/pefile.py", line 25, in <module>
    __version__ = '1.2.10-%d' % int( __revision__[21:-2] )
ValueError: invalid literal for int() with base 10: ''
```

**Comment by joachimmetz** [comment]
I guess this is what you were mentioning regarding svn filling in the version number.

**Comment by smclinden** [comment]
This continues to be a problem with the latest git release:
python setup.py
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import pefile
  File "/usr/src/forensic/pefile/pefile.py", line 25, in <module>
    __version__ = '1.2.10-%d' % int( __revision__[21:-2] )
ValueError: invalid literal for int() with base 10: ''

**Comment by nyx0** [comment]
@erocarrera Any updates?

**Comment by smclinden** [comment]
The current version is 1.2.10-139. You should be able to patch the code for a temporary fix.

**Comment by sh3dow** [comment]
i have this problem with setup.py in windows last night so i create new setup.py 
file and it works like a charm

`from distutils.core import setup

setup(
    name='pefile',
    version='pefile.__version__,',
    packages=['ordlookup'],
    url='http://code.google.com/p/pefile/',
    license='The MIT License (MIT)',
    author='Ero Carrera',
    author_email='ero.carrera@gmail.com',
    description='pefile, Portable Executable reader module'
)`

**Comment by nyx0** [comment]
@sh3dow I think you can replace `http://code.google.com/p/pefile/` by `https://github.com/erocarrera/pefile/`

**Comment by ventz** [comment]
@sh3dow - thanks - that held.
@nyx0 - for some reason the latest git checkout still won't work. Error:

Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import pefile
  File "/private/tmp/pefile-pefile-1.2.10-139/pefile.py", line 25, in <module>
    __version__ = '1.2.10-%d' % int( __revision__[21:-2] )
ValueError: invalid literal for int() with base 10: ''

**Comment by joachimmetz** [comment]
Have a look at the attached PR https://github.com/erocarrera/pefile/pull/72/files

**Comment by ventz** [comment]
@joachimmetz - much thanks!

Confirming that ^ (https://github.com/erocarrera/pefile/pull/72/files) worked!

**Comment by jpouellet** [comment]
I required an equivalent patch as well.

+1 to this still being a problem

**Comment by blshkv** [comment]
Please do not modify the following:
````
+-#!/usr/bin/env python
 ++#!/usr/bin/python
```

The original line is correct

**Comment by joachimmetz** [comment]
To be verbose both are correct, see a discussion here of some of the pros and cons:
http://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my

**Comment by blshkv** [comment]
not really. The second one is not flexable and will fail if python is installed to a different path. It also doesn't allow a user to specify which version of python he wants to use.

For example, /usr/bin/python points to python3.4 in my system. A software would fail to run if it does not support python3.4.

The first line allows me to run "python2 /path/software.py"

**Comment by joachimmetz** [comment]
> The first line allows me to run "python2 /path/software.py"

This will work with both versions since you specify the interpreter. If this fails it likely is due to python2 missing from your PATH.

You can run this with both version the shebang is only relevant when no interpreter is specified e.g.
```
/path/software.py
```

Where in the case of ```env``` the environment is scanned.

From: https://en.wikipedia.org/wiki/Env
> Note that it is possible to specify the interpreter without using env, by giving the full path of the python interpreter. A problem with that approach is that on different computer systems, the exact path may be different. By instead using env as in the example, the interpreter is searched for and located at the time the script is run. This makes the script more portable, but also increases the risk that the wrong interpreter is selected because it searches for a match in every directory on the executable search path. It also suffers from the same problem in that the path to the env binary may also be different on a per-machine basis.

**Comment by blshkv** [comment]
well, we can argue infinitely, but the truth is I don't' really care what it will be at the end :P . At gentoo, we have https://wiki.gentoo.org/wiki/Project:Python/python-utils-r1#python_fix_shebang . python_fix_shebang will do it job automatically and normalise all scripts to the proper value.

**Comment by joachimmetz** [comment]
If you don't care then why your initial remark and follow up argumentation? I'm also not trying to arguing with you, largely pointing you to documentation that refutes your claims.

**Comment by blshkv** [comment]
https://blogs.gentoo.org/mgorny/2016/02/08/a-quick-note-on-portable-shebangs
```
#!/usr/bin/python  # BAD: absolute path is non-portable
```

**Comment by erocarrera** [comment]
Fixed.
