### ISSUE TITLE
pefile not showing all imports 

### ISSUE THREAD

**Issue by frbapolkosnik** [erocarrera/pefile#66]
A colleague of mine stepped across this dll that breaks pefile's import parsing.

Pefile shows only two imported dlls (msjet35.dll and kernel32.dll), but going through the structures USER32.dll and ADVAPI32.dll imports are missing,

MD5 is 954ceb4d7c7dc5e94ea237cf96d387a3

http://pedump.me/954ceb4d7c7dc5e94ea237cf96d387a3/

I think that VirusTotal is using pefile since it also shows the truncated imports:
https://www.virustotal.com/en/file/66c74e4c9dbd1d33b22f63cd0318b72dea88f9dbb4d36a3383d3da20b037d42e/analysis/

![msrd2x35_imports](https://cloud.githubusercontent.com/assets/4399806/7326087/c1316d20-ea90-11e4-9c94-4b4946dfab6f.gif)

**Comment by frbapolkosnik** [comment]
pefile throws an error on the third import, and because of that it breaks out of the while loop, and stops processing the rest of the imports...

I've added some info to the error messages:
Error parsing the import directory. Invalid Import data at RVA: 0x503c (Invalid Import data at RVA: 0x5e03c (Invalid Import Table information. originalFirstThunk:0x5e178  FirstThunk:0x5e298 Both ILT and IAT appear to be broken.)

**Comment by webstergd** [comment]
I am doing a port of PEInfo now. I will see if I can tackle this and push a patch to both systems

**Comment by erocarrera** [comment]
pefile version 2016.3.4 fixes this issue.
