### ISSUE TITLE
Direct Interface for Address Translation

### ISSUE THREAD

**Issue by ZSShen** [erocarrera/pefile#73]
Is it possible to add a new public interface for address translation?
Like: RVA to physical address or physical address to RVA
More specifically, given a RVA of the analyzed PE file, the operation can output the corresponding physical address, and vise versa.

It maybe helpful for volume sample processing.

**Comment by ZSShen** [comment]
If it is possible, I can help to support such interfaces.

**Comment by erocarrera** [comment]
RVA to absolute is fairly easy, I'm unsure of what do you mean by
translating to physical address, that would require privileged access to
find out where the OS is mapping the virtual addresses to physical memory
and only work for PEs that are mapped in memory. pefile only parses the
structures but does not attempt to map the file in the address space as
described by the section headers. Can you provide more details?

**Comment by ZSShen** [comment]
Sorry, I did not specify the term "Physical Address" well.
It should be "RawOffset" within the binary file.

And you are right, the interface is fairly easy. 
A simple translation from VirtualOffset to RawOffset or from RawOffset to VirtualOffset.
Just Like:
```python
import pefile
pe = pefile.PE('notepad.exe')

# Translate from virtual offset to physical offset.
virtual_ofst = 1001;
physical_ofst = pe.address_virtual_to_physical(virtual_ofst)

# Translate from physical offset to virtual offset.
physical_ofst = 7c01;
virtual_ofst = pe.address_physical_to_virtual(physical_ofst)
```

**Comment by fergofrog** [comment]
Do the functions `get_offset_from_rva` and `get_rva_from_offset` in the PE class fit the bill? For example:

```python
import pefile
pe = pefile.PE('notepad.exe')

# Translate from virtual offset to physical offset.
virtual_ofst = 1001;
physical_ofst = pe.get_offset_from_rva(virtual_ofst)

# Translate from physical offset to virtual offset.
physical_ofst = 7c01;
virtual_ofst = pe.get_rva_from_offset(physical_ofst)
```

**Comment by erocarrera** [comment]
Hi there,

Sorry for the slow reply. As you correctly guessed, those two functions do
what you want.

--
Ero
