### ISSUE TITLE
DIRECTORY_ENTRY_EXPORT DLL name

### ISSUE THREAD

**Issue by iverson155** [erocarrera/pefile#75]
I've been looking for a way to parse the export DLL name, which directly precedes the first export name of DIRECTORY_ENTRY_EXPORT.  Here's an example of the location of the DLL name within the file:

bash-3.2# xxd secur32.dll
...
00008a0: 4a00 4b00 5365 6375 7233 322e 646c 6c00  J.K.Secur32.dll.
00008b0: 4163 6365 7074 5365 6375 7269 7479 436f  AcceptSecurityCo
00008c0: 6e74 6578 7400 4163 7175 6972 6543 7265  ntext.AcquireCre
...

And here's my error-prone workaround using pefile to parse the first export name and re.findall to locate the preceding string.  It would be great if this name were accessible via DIRECTORY_ENTRY_EXPORT.struct:

bash-3.2# python
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pefile
>>> pe = pefile.PE('secur32.dll')
>>> exp = pe.DIRECTORY_ENTRY_EXPORT.symbols[0].name
>>> exp
'AcceptSecurityContext'
>>> filedata = open('secur32.dll','r').read()
>>> import re
>>> dllname = re.findall('([^\x00]+)\x00'+exp,filedata)
>>> if len(dllname):
...     print dllname[0]
... 
Secur32.dll

**Comment by nyx0** [comment]
Maybe try with:
``` python
import pefile
pe = pefile.PE('secur32.dll')
for i in pe.DIRECTORY_ENTRY_EXPORT.symbols:
    print i.name
```

**Comment by erocarrera** [comment]
Hi there,

The Name field in pe.DIRECTORY_ENTRY_EXPORT.struct contains the RVA to the
name of the DLL. You can get the string easily with:

print pe.get_string_at_rva(pe.DIRECTORY_ENTRY_EXPORT.struct.Name)

Although I should probably do something similar to what I do for imports
and provide the name of the file as an attribute, already fetched.
