### ISSUE TITLE
Feedback about the installation

### ISSUE THREAD

**Issue by WagnerGMD** [erocarrera/pefile#77]
`(1)pip install pefile`
`(2)pip install pefile --allow-external=pefile --allow-unverified=pefile`
Hello,

first of all, I performed an update for pip (v7.1.2) and checked Python (stable still v3.4.3).
**By default**, under Windows <del>(8.1)</del>, pip <del>(original was v6.0.8)</del> wants to install the (1) pefile-1.2.10-114. Intead of the latest one : (2) pefile-1.2.10-139.
For the both, the installation results in a failure. I created some logs files (just ask).

After a little while, I discover [this discussion (issue n°36).](https://github.com/erocarrera/pefile/issues/36)
`https://bitbucket.org/mlaferrera/pefile-python3 ## pefile==? This repository is no more available.`
`https://github.com/mlaferrera/python3-pefile ## pefile==1.2.10.post139 Seem's to be replace by this one. `
`https://github.com/BlackXeronic/pefile_py3k ## pefile==1.2.10.post123`
`https://github.com/BlackXeronic/pefile_py3 ## pefile==1.2.10.post139`
For each one, it seem's to be a success; pip report the right version via show. Via search, pip can't find them.
`pip search "pefile"`

So, I'm wondering, the trouble as something to do with the version of Python ? Which one should be considered as the reference ?
I don't know but this feedback might help someone. And you may want to publish a warning (or note) about.

**Comment by mlaferrera** [comment]
I transitioned from bitbucket to github. Thought this isn't the officially supported version, you can get to a working Python3 only version at https://github.com/mlaferrera/python3-pefile

I've been using it extensively for the last year or so without issue.

**Comment by WagnerGMD** [comment]
Thank you for the answer and the feedback, it's good to know.
