### ISSUE TITLE
version number violates common guidelines

### ISSUE THREAD

**Issue by shibumi** [erocarrera/pefile#85]
Hello,
I want to package pefile for Archlinux. Could you please avoid version-numbers like `pefile-1.2.10-139`. The last part is normally for the distribution for counting their rebuilds. Would be awesome if you find a away to avoid `-` in your version number, please prefer `.`

thx. 

best regards

Chris

**Comment by JonathonReinhart** [comment]
+1 I agree with @shibumi.  I highly suggest following [Semantic Versioning](http://semver.org/)'s `major.minor.patch` scheme.

**Comment by erocarrera** [comment]
Fixed. The new versioning scheme should not run into these issues anymore.
