### ISSUE TITLE
pefile-1.2.10-139 doesn't build

### ISSUE THREAD

**Issue by shibumi** [erocarrera/pefile#86]
Hello,
I have trouble with building pefile-1.2.10-139. 

Here is what I get for python2:
```
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import pefile
  File "/home/user/export/archlinux/python2-pefile/src/pefile-pefile-1.2.10-139/pefile.py", line 25, in <module>
    __version__ = '1.2.10-%d' % int( __revision__[21:-2] )
ValueError: invalid literal for int() with base 10: ''
```

And here is what I get for python3:
```
  File "setup.py", line 5
    except ImportError, excp:
                      ^
SyntaxError: invalid syntax
```

**Comment by nyx0** [comment]
For the first one I think you have to pull the repo.
For the python3, we are waiting to @erocarrera to merge our PR. (see #69)

**Comment by shibumi** [comment]
@nyx0 you mean I have to pull the bleeding edge repository? why? why are you releasing a broken release oO

**Comment by nyx0** [comment]
Yes, sorry for my mistake. (only old binaries are affected, Win2000)
As I said we are waiting for @erocarrera to try to do a better versioning.

**Comment by shibumi** [comment]
@nyx0 ok so I will wait with packaging pefile for archlinux until it's fixed :)

**Comment by erocarrera** [comment]
Hopefully this issue has been finally addresses in the latest release.
