### ISSUE TITLE
TypeError: get_data() takes at least 2 arguments (1 given)

### ISSUE THREAD

**Issue by b3mb4m** [erocarrera/pefile#88]
pefile is newest version.

`import pefile`
`pe = pefile.PE( "myexe.exe")`
`print pe.sections[0].get_data()`

`  File "/root/Desktop/qweqwe.py", line 11, in testpe`
    `print pe.sections[0].get_data()`
`TypeError: get_data() takes at least 2 arguments (1 given)`

OS:
`Linux b3mb4m 4.0.0-kali1-686-pae #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) i686 GNU/Linux
`

Pefile doesnt support investigate pe files on linux ? Or its just bug ? On win7 its working without any problem.

**Comment by erocarrera** [comment]
It should work. Do you have an example file? or does it happen with any PE?

**Comment by nyx0** [comment]
@b3mb4m Can you give the version of pefile just to be sure. Usually it's an old version installed on Kali.
`pefile.__version__`
