### ISSUE TITLE
future module not automatically installed by pip

### ISSUE THREAD

**Issue by matysek** [erocarrera/pefile#93]
When I try to install downloaded pefile-2016.3.4 with pip I get this traceback:
```
» pip install -e /tmp/pefile-2016.3.4                                                                         
Obtaining file:///tmp/pefile-2016.3.4
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pefile-2016.3.4/setup.py", line 13, in <module>
        import pefile
      File "/tmp/pefile-2016.3.4/pefile.py", line 26, in <module>
        from past.builtins import cmp
    ImportError: No module named 'past'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pefile-2016.3.4
```

The issue here is circular dependency:
- `pefile` module depends on `future`
- `pip install` should install `future` automatically
- however `setup.py` imports version from `pefile` module before pip is able to install `future` module

**Comment by shibumi** [comment]
Hello,
I am currently packaging pefile for the AUR (Arch Linux User Repository) and I have the same problem when I try to build pefile for python2 or python3:

```
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    import pefile
  File "/home/chris/export/archlinux/python2-pefile/src/pefile-2016.3.4/pefile.py", line 26, in <module>
    from past.builtins import cmp
ImportError: No module named 'past'
```

**Comment by matysek** [comment]
Probably the proper fix would be:
- not import `pefile` in setup.py
- in setup.py parse file `pefile.py` as a text file and get the necessary attributes: `__version__`, etc.

**Comment by shibumi** [comment]
@matysek 
I hope the developer can fix this issue fast with a new release.. A lot of people in arch linux community are waiting for this software

**Comment by shibumi** [comment]
@matysek 
I think you need python-six and python-future for compiling it. Seems to work when I have these to libs installed.

**Comment by erocarrera** [comment]
Thanks matysek for the fix. I'll merge it into pefile.
