### ISSUE TITLE
TypeError: 'long' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by zhp1254** [erocarrera/pefile#96]
errinfo:
print pefile.PE(r'C:\Users\Administrator\Desktop\ZKEYS\AutoHost.exe')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pefile.py", line 4238, in __str__
    return self.dump_info()
  File "pefile.py", line 4302, in dump_info
    dump.add_lines(section.dump())
  File "pefile.py", line 908, in dump
    if isinstance(val_str[0], int):
TypeError: 'long' object has no attribute '__getitem__'

sysinfo:
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32

**Comment by erocarrera** [comment]
Could you provide me with the hash or the AutoHost.exe file? I'd love to reproduce the issue.

**Comment by Takouyii** [comment]
I tried to use this module just now for the first time,and encountered the same problem.I don't know what to do.

**Comment by rdb0101** [comment]
Has there been a resolution for this issue?

**Comment by sbobovyc** [comment]
pefile.py:895

Should be if isinstance(val, int) or isinstance(val, long) instead of
if isinstance(val, int) or isinstance(val, int):

**Comment by arthurlucien** [comment]
@sbobovyc Yeah，it's works!

**Comment by stephenrauch** [comment]
Bug was fixed here: https://github.com/erocarrera/pefile/commit/34a3f19d8eb058ba2040c1edac8f9dcf7e86c14a

The development tip is [here](https://raw.githubusercontent.com/erocarrera/pefile/master/pefile.py).

**Comment by sbobovyc** [comment]
Version installed by pip ('2016.3.28') has this bug.

**Comment by rdb0101** [comment]
that worked! thanks!
