### ISSUE TITLE
Error parsing Rich Headers

### ISSUE THREAD

**Issue by kbtoys** [erocarrera/pefile#97]
A rich header can be larger than 0x80 bytes.  

This section of code needs to change:
        # Read a block of data
        try:
            rich_data = self.get_data(0x80, 0x80)
            if len(rich_data) != 0x80:
                return None
            data = list(struct.unpack("<32I", rich_data))
        except PEFormatError:
            return None

Suggested rewrite:
        # Read a block of data
        try:
            rich_data = self.get_data(0x80)
            data = list(struct.unpack("<%sI" % (len(rich_data/4)), rich_data))
            if RICH not in data:
                return None
        except PEFormatError:
            return None

**Comment by erocarrera** [comment]
Implemented in commit 465b2ee
