### ISSUE TITLE
Unable to pip install pefile

### ISSUE THREAD

**Issue by RyPeck** [erocarrera/pefile#99]
```
$ pip install pefile
Collecting pefile
  Could not find a version that satisfies the requirement pefile (from versions: )
No matching distribution found for pefile
```

Attempting to navigate to https://pypi.python.org/pypi/pefile/1.2.10-139 (first link that comes up in PyPI searching for pefile) I get a 404.

Not sure if this is something caused by PyPI or pefile. Please advise! Thank you for all your hard work @erocarrera!

**Comment by erocarrera** [comment]
To the best of my knowledge it's an issue with pypi, see #92. The search index appears to not have been refreshed recently.

**Comment by RyPeck** [comment]
Thanks for the update @erocarrera. Working for me now.
